services:
  gateaway:
    build: gateaway
    ports:
      - "8080:8080" # api.krakow.pl
      - "3000:3000" # login.gov.pl
      - "80:80" # frontend
      - "9000:9000" # volcon api admin
    depends_on:
      - login_gov_mock
      - volcon_api
      - frontend
    networks:
      - volcon-network
  login_gov_mock:
    build: login_gov_mock
    networks:
      - volcon-network
    environment:
      - MAIN_BACKEND_TOKEN_ATTACH_URL=http://localhost:8080/volcon/attach_token/
  volcon_api:
    build: volcon_api
    networks:
      - volcon-network
    depends_on:
      - typesense
  frontend:
    build: frontend
    networks:
      - volcon-network
  typesense:
    image: typesense/typesense:29.0
    restart: on-failure
    ports:
      - "8108:8108"
    command: '--data-dir /data --api-key=qwerty123 --enable-cors'
    networks:
      - volcon-network

networks:
  volcon-network:
    driver: bridge
