services:
  gateaway:
    build: gateaway
    ports:
      - "8080:8080" # api.krakow.pl
      - "3000:3000" # login.gov.pl
    depends_on:
      - login_gov_mock
    networks:
      - volcon-network
  login_gov_mock:
    build: login_gov_mock
    networks:
      - volcon-network

networks:
  volcon-network:
    driver: bridge
