# Generated by Django 4.2.4 on 2025-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('external_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('pesel', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('agreement_file', models.BinaryField(blank=True, null=True)),
                ('supervisor_id', models.IntegerField()),
                ('institution_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('institution_id', models.IntegerField()),
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_loc', models.JSONField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('parent_group_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('dates', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('regon', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('is_company', models.BooleanField(default=False)),
                ('id_user', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('desc', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('user_id', models.IntegerField()),
                ('privilege_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('privilege', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('institution_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('dates', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
